#ifndef DATA_TYPES_H
#define DATA_TYPES_H

/* =============================================================
   WORD LADDER - data_types.h
   WORD_LENGTH 3 → 3-letter mode (words3.txt)
   WORD_LENGTH 6 → 6-letter mode (words6.txt)
   ============================================================= */

#define WORD_LENGTH 3

/* Actions: encoded as (position * 26 + letter_index)
   156 values cover positions 0-5 for up to 6-letter words.
   Result() rejects actions where position >= WORD_LENGTH.       */
enum ACTIONS {
    CHANGE_POS0_TO_A,CHANGE_POS0_TO_B,CHANGE_POS0_TO_C,CHANGE_POS0_TO_D,
    CHANGE_POS0_TO_E,CHANGE_POS0_TO_F,CHANGE_POS0_TO_G,CHANGE_POS0_TO_H,
    CHANGE_POS0_TO_I,CHANGE_POS0_TO_J,CHANGE_POS0_TO_K,CHANGE_POS0_TO_L,
    CHANGE_POS0_TO_M,CHANGE_POS0_TO_N,CHANGE_POS0_TO_O,CHANGE_POS0_TO_P,
    CHANGE_POS0_TO_Q,CHANGE_POS0_TO_R,CHANGE_POS0_TO_S,CHANGE_POS0_TO_T,
    CHANGE_POS0_TO_U,CHANGE_POS0_TO_V,CHANGE_POS0_TO_W,CHANGE_POS0_TO_X,
    CHANGE_POS0_TO_Y,CHANGE_POS0_TO_Z,
    CHANGE_POS1_TO_A,CHANGE_POS1_TO_B,CHANGE_POS1_TO_C,CHANGE_POS1_TO_D,
    CHANGE_POS1_TO_E,CHANGE_POS1_TO_F,CHANGE_POS1_TO_G,CHANGE_POS1_TO_H,
    CHANGE_POS1_TO_I,CHANGE_POS1_TO_J,CHANGE_POS1_TO_K,CHANGE_POS1_TO_L,
    CHANGE_POS1_TO_M,CHANGE_POS1_TO_N,CHANGE_POS1_TO_O,CHANGE_POS1_TO_P,
    CHANGE_POS1_TO_Q,CHANGE_POS1_TO_R,CHANGE_POS1_TO_S,CHANGE_POS1_TO_T,
    CHANGE_POS1_TO_U,CHANGE_POS1_TO_V,CHANGE_POS1_TO_W,CHANGE_POS1_TO_X,
    CHANGE_POS1_TO_Y,CHANGE_POS1_TO_Z,
    CHANGE_POS2_TO_A,CHANGE_POS2_TO_B,CHANGE_POS2_TO_C,CHANGE_POS2_TO_D,
    CHANGE_POS2_TO_E,CHANGE_POS2_TO_F,CHANGE_POS2_TO_G,CHANGE_POS2_TO_H,
    CHANGE_POS2_TO_I,CHANGE_POS2_TO_J,CHANGE_POS2_TO_K,CHANGE_POS2_TO_L,
    CHANGE_POS2_TO_M,CHANGE_POS2_TO_N,CHANGE_POS2_TO_O,CHANGE_POS2_TO_P,
    CHANGE_POS2_TO_Q,CHANGE_POS2_TO_R,CHANGE_POS2_TO_S,CHANGE_POS2_TO_T,
    CHANGE_POS2_TO_U,CHANGE_POS2_TO_V,CHANGE_POS2_TO_W,CHANGE_POS2_TO_X,
    CHANGE_POS2_TO_Y,CHANGE_POS2_TO_Z,
    CHANGE_POS3_TO_A,CHANGE_POS3_TO_B,CHANGE_POS3_TO_C,CHANGE_POS3_TO_D,
    CHANGE_POS3_TO_E,CHANGE_POS3_TO_F,CHANGE_POS3_TO_G,CHANGE_POS3_TO_H,
    CHANGE_POS3_TO_I,CHANGE_POS3_TO_J,CHANGE_POS3_TO_K,CHANGE_POS3_TO_L,
    CHANGE_POS3_TO_M,CHANGE_POS3_TO_N,CHANGE_POS3_TO_O,CHANGE_POS3_TO_P,
    CHANGE_POS3_TO_Q,CHANGE_POS3_TO_R,CHANGE_POS3_TO_S,CHANGE_POS3_TO_T,
    CHANGE_POS3_TO_U,CHANGE_POS3_TO_V,CHANGE_POS3_TO_W,CHANGE_POS3_TO_X,
    CHANGE_POS3_TO_Y,CHANGE_POS3_TO_Z,
    CHANGE_POS4_TO_A,CHANGE_POS4_TO_B,CHANGE_POS4_TO_C,CHANGE_POS4_TO_D,
    CHANGE_POS4_TO_E,CHANGE_POS4_TO_F,CHANGE_POS4_TO_G,CHANGE_POS4_TO_H,
    CHANGE_POS4_TO_I,CHANGE_POS4_TO_J,CHANGE_POS4_TO_K,CHANGE_POS4_TO_L,
    CHANGE_POS4_TO_M,CHANGE_POS4_TO_N,CHANGE_POS4_TO_O,CHANGE_POS4_TO_P,
    CHANGE_POS4_TO_Q,CHANGE_POS4_TO_R,CHANGE_POS4_TO_S,CHANGE_POS4_TO_T,
    CHANGE_POS4_TO_U,CHANGE_POS4_TO_V,CHANGE_POS4_TO_W,CHANGE_POS4_TO_X,
    CHANGE_POS4_TO_Y,CHANGE_POS4_TO_Z,
    CHANGE_POS5_TO_A,CHANGE_POS5_TO_B,CHANGE_POS5_TO_C,CHANGE_POS5_TO_D,
    CHANGE_POS5_TO_E,CHANGE_POS5_TO_F,CHANGE_POS5_TO_G,CHANGE_POS5_TO_H,
    CHANGE_POS5_TO_I,CHANGE_POS5_TO_J,CHANGE_POS5_TO_K,CHANGE_POS5_TO_L,
    CHANGE_POS5_TO_M,CHANGE_POS5_TO_N,CHANGE_POS5_TO_O,CHANGE_POS5_TO_P,
    CHANGE_POS5_TO_Q,CHANGE_POS5_TO_R,CHANGE_POS5_TO_S,CHANGE_POS5_TO_T,
    CHANGE_POS5_TO_U,CHANGE_POS5_TO_V,CHANGE_POS5_TO_W,CHANGE_POS5_TO_X,
    CHANGE_POS5_TO_Y,CHANGE_POS5_TO_Z
};

typedef struct State {
    char  word[7];   /* up to 6 letters + '\0' */
    float h_n;       /* heuristic value         */
} State;

/* ===== DO NOT CHANGE BELOW ===== */
enum METHODS {
    BreastFirstSearch=1, UniformCostSearch=2,    DepthFirstSearch=3,
    DepthLimitedSearch=4,IterativeDeepeningSearch=5, GreedySearch=6,
    AStarSearch=7,       GeneralizedAStarSearch=8
};
typedef struct Transition_Model { State new_state; float step_cost; } Transition_Model;
typedef struct Node {
    State state; float path_cost; enum ACTIONS action;
    struct Node *parent; int Number_of_Child;
} Node;
typedef struct Queue { Node *node; struct Queue *next; } Queue;

#endif
